apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesBoard
  labels:
    app: salesBoard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesBoard
  template:
    metadata:
      labels:
        app: salesBoard
    spec:
      containers:
        - name: salesBoard
          image: username/salesBoard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5